language: cpp

compiler:
  - gcc
 
env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "JiOV7rEEUj+AzmkMKX5a1PG6xZQLw17T5FQmb/wTKymSl5Yb2VJk1wqsoJWecRD/RDzFAo5xRS5EN6BxbYwePQZvNhBIXECrTWA5FHmCXkQt8QF+78a0vVyxIICwNhraWRNpvPop72/FSuFaN6NVAK2we/i7rnthCd/KJvOksnc="

addons:
  coverity_scan:
    project:
      name: "KonstantinKuklin/HandlerSocket-Plugin-for-MySQL"
      description: "Your project description here"
    notification_email: konstantin.kuklin@gmail.com
    build_command_prepend:
      - "./autogen.sh"
      - "./configure --with-mysql-source=mysql-5.5/"
    build_command: "make -j4"
    branch_pattern: coverity_scan

before_script:
  # prepare depends
  - sudo apt-get update
  - sudo apt-get install mysql-server-5.5 mysql-client-5.5 libmysqlclient-dev mysql-source-5.5 libdbd-mysql-perl
  # configure for make
  - ./autogen.sh
  - cp /usr/src/mysql/mysql-source-5.5.tar.gz .
  - tar -zxf mysql-source-5.5.tar.gz
  - ./configure --with-mysql-source=mysql-5.5/
  - make
  - sudo make install
  # copy config files for mysql
  - sudo cp ./regtest/conf/hs.cnf /etc/mysql/conf.d/hs.cnf
  # build HS perl plugins for regtests
  - cd ./perl-Net-HandlerSocket
  - perl Makefile.PL
  - make
  - sudo make install
  # restart mysql servise to get changes
  - sudo service mysql restart
  # debug is mysql get hs
  - mysql -e "SHOW PROCESSLIST;"
  # cd to root HS dir
  - cd ../
  # where is coverity send build

script:
  - cd ./regtest
  - make