language: cpp

compiler:
  - gcc

env:
  global:
    - ci_home=`pwd`
    # Variables for Coverity scan
    - STANDARD_BUILD_COMMAND="make"
    - COVERITY_SCAN_PROJECT_NAME="KonstantinKuklin%2FHandlerSocket-Plugin-for-MySQL"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="konstantin.kuklin@gmail.com"
    # Regular expression selects on which branches to run analysis
    # Be aware of quotas. Do not run on every branch/commit
    - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"

    # Optionally execute a command immediately before cov-build, i.e.
    # pre-configuration required for the COVERITY_SCAN_BUILD_COMMAND
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND=""

    # Insert the cov-build build commmand here
    - COVERITY_SCAN_BUILD_COMMAND=$STANDARD_BUILD_COMMAND

    # COVERITY_SCAN_TOKEN via "travis encrypt" using the repo's public key
    - COVERITY_SCAN_TOKEN: "H67c90X2MdE6OgEVXuhu8A"

    # ---- END Project-specific configuration

    - COVERITY_SCAN_BUILD_URL="https://gist.githubusercontent.com/KonstantinKuklin/63df870cb63519d49bce/raw"
    - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"

before_script:
  # prepare depends
  - sudo apt-get update
  - sudo apt-get install mysql-server-5.5 mysql-client-5.5 libmysqlclient-dev mysql-source-5.5 libdbd-mysql-perl
  # configure for make
  - ./autogen.sh
  - echo $ci_home
  - cp /usr/src/mysql/mysql-source-5.5.tar.gz $ci_home
  - pwd
  - tar -zxf $ci_home/mysql-source-5.5.tar.gz
  - ./configure --with-mysql-source=$ci_home/mysql-5.5/

script:
  - eval "$COVERITY_SCAN_BUILD"
  - sudo make install
  # copy config files for mysql
  - sudo cp ./regtest/conf/hs.cnf /etc/mysql/conf.d/hs.cnf
  # build HS perl plugins for regtests
  - cd ./perl-Net-HandlerSocket
  - perl Makefile.PL
  - make
  - sudo make install
  # restart mysql servise to get changes
  - sudo service mysql restart
  # debug is mysql get hs
  - mysql -e "SHOW PROCESSLIST;"
  # cd to root HS dir
  - cd ../regtest
  - make
